apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-api
  namespace: dashboard-api
spec:
  selector:
    matchLabels:
      app: dashboard-api
  replicas: 1
  template:
    metadata:
      labels:
        app: dashboard-api
    spec:
      containers:
        - name: dashboard-api
          image: CONTAINER_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 4000